# Generated by Django 5.1 on 2024-11-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenescompra',
            name='fecha_creacion',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='fecha_entrega',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
        ),
        migrations.DeleteModel(
            name='CarroCompra',
        ),
    ]
