# Generated by Django 3.2.25 on 2024-11-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20241129_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('nro_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_pedido', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_pedido',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.producto')),
            ],
        ),
    ]
