# Generated by Django 3.2.25 on 2024-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20241129_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenescompra',
            name='cantidad',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='fecha_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
