# Generated by Django 3.2.25 on 2024-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20241130_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenescompra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
