# Generated by Django 3.2.25 on 2024-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20241130_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenescompra',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
